### ISSUE TITLE
Lists in sidebar could be styled better

### ISSUE THREAD

**Issue by ryelle** [ryelle/Cucina#1]
Cooking blogs seem to use lists a lot, for recent posts, or categories, or whatever. Our lists should look better.

**List as Navigation**
- http://smittenkitchen.com/
- http://www.thekitchn.com/

**Lists as secondary way of navigating recipes**
- http://www.skinnytaste.com/ has a recipe list buried in the skinny two-column sidebar
- even Williams-Sonoma uses lists in their recipe section... http://www.williams-sonoma.com/recipe/chicken-tagine-with-lemon-and-olives.html
- http://mylittleexpatkitchen.blogspot.com/
- http://mattbites.com/

Anyway, I think you get the idea-- sidebars are popular, and we should make sure they look good in Cucina. (two col sidebars are also strangely popular... probably because it allows for the long-skinny advertisement. since we're planning on this for .org, maybe we should make that sort of thing easier?)

**Comment by melchoyce** [comment]
![screen shot 2015-02-13 at 11 25 28 am](https://cloud.githubusercontent.com/assets/2846578/6190861/0bf64e0c-b373-11e4-9ffa-db6871aa84eb.png)

File in Dropbox.
